services:
  - type: web
    name: social
    plan: starter
    repo: https://github.com/colburncodes/social.git
    buildCommand: yarn --frozen-lockfile --prod=false &&
      blitz prisma generate &&
      blitz build &&
      blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: social_db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: false

databases:
  - name: social_db
    plan: starter